AMAZON_LOGO_LOCATOR = ("//div[@class='a-section a-padding-medium auth-workflow']/div[@class='a-section a-spacing-none auth-navbar']/div[@class='a-section a-spacing-medium a-text-center']//i[@class='a-icon a-icon-logo']")
EMAIL_FIELD_LOCATOR = ("//div[@class='a-row a-spacing-base']//input[@class='a-input-text a-span12 auth-autofocus auth-required-field']")
BUTTON_CONTINUE_LOCATOR = ("//div[@class='a-section']/span[@class='a-button a-button-span12 a-button-primary']/span[@class='a-button-inner']/input[@class='a-button-input']")
CONDITION_OF_USE_LOCATOR = ("//div[@class='a-section']/div[@id='legalTextRow']/a[text()='Conditions of Use']")
PRIVACY_NOTICE_LOCATOR = ("//div[@class='a-section']/div[@id='legalTextRow']/a[text()='Privacy Notice']")
NEED_HELP_BUTTON_LOCATOR = ("//div[@class='a-section']/div[@class='a-row a-expander-container a-expander-inline-container']//span[@class='a-expander-prompt']")
FORGOT_YOUR_PASSWORD_BUTTON_LOCATOR = ("//div[@class='a-section']//div[@class='a-expander-content a-expander-inline-content a-expander-inner a-expander-content-expanded']//a[@id='auth-fpp-link-bottom']")
OTHER_ISSUES_WITH_SIGN_IN = ("//div[@class='a-section']//div[@class='a-expander-content a-expander-inline-content a-expander-inner a-expander-content-expanded']//a[@id='ap-other-signin-issues-link']")
CREATE_AMAZON_ACCOUNT_LOCATOR = ("//div[@class='a-section a-spacing-base']/span[@class='a-button a-button-span12 a-button-base']/span[@class='a-button-inner']/a[@id='createAccountSubmit']")