AMAZON_LOGO_LOCATOR= "//div[@class='a-section a-padding-medium auth-workflow']/div[@class='a-section a-spacing-none auth-navbar']/div[@class='a-section a-spacing-medium a-text-center']//i[@class='a-icon a-icon-logo']"
EMAIL_FIELD_LOCATOR= "//input[@class='a-input-text a-span12 auth-autofocus auth-required-field']"
CONTINUE_BUTTON = "//div[@class='a-section']/span[@class='a-button a-button-span12 a-button-primary']/span[@class='a-button-inner']/input[@class='a-button-input']"
NEED_HELP_LINK_LOCATOR = "//div[@class='a-section']//a[@class='a-expander-header a-declarative a-expander-inline-header a-link-expander']/span[@class='a-expander-prompt']"
FORGOT_YOUR_PASSWORD_LOCATOR = "//div[@class='a-row a-expander-container a-expander-inline-container']//a[@id='auth-fpp-link-bottom']"
OTHER_ISSUES_WITH_SIGN_IN_LOCATOR = "//div[@class='a-section']//div[@class='a-expander-content a-expander-inline-content a-expander-inner a-expander-content-expanded']//a[@id='ap-other-signin-issues-link']"
CONDITIONS_OF_USE_LINK_LOCATOR = "//div[@class='a-section']/div[@id='legalTextRow']/a[text()='Conditions of Use']"
PRIVACY_NOTICE_LINK_LOCATOR = "//div[@class='a-section']/div[@id='legalTextRow']/a[@id='ap-other-signin-issues-link']"
CREATE_AMAZON_ACCOUNT_LOCATOR = "//div[@class='a-section']//span[@class='a-button a-button-span12 a-button-base']/span[@class='a-button-inner']/a[@id='createAccountSubmit']"